version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    #image: wurstmeister/kafka
    build: 
        context: ./KAFKA
        dockerfile: Dockerfile
    ports:
      - "9092:9092"
    links:
      - zookeeper:zk
    environment:
       KAFKA_ADVERTISED_PORT: 9092
       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
       KAFKA_ADVERTISED_HOST_NAME: 192.168.1.49
       KAFKA_CREATE_TOPICS: "passover-rooms-visitorcounts:1:1 passover-position-messages:1:1"
    volumes:
       - /Users/alanhared/Documents/projet-Datamind/datamint/docker-compose-kafka-zookeeper/KAFKA/LOG-KAFKA:/tmp/kafka-logs
  datamint:
     build: 
         context: ./DATAMINT
         dockerfile: Dockerfile
     container_name: datamint
     links:
      - kafka
     volumes:
       - /Users/alanhared/Documents/projet-Datamind/datamint/docker-compose-kafka-zookeeper/DATAMINT/LOG-DATAMINT:/tmp/passover
       
