version: '2'
services:
  zookeeper:
    #image: wurstmeister/zookeeper
    build: 
       context: ./ZOOKEEPER 
       dockerfile: Dockerfile
    ports:
      - "2181:2181"
      - "22888:23888"
      - "32888:33888"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVERS: 192.168.1.27:32888:33888 localhost:22888:23888
  #kafka:
  #  #image: wurstmeister/kafka
  #  build: 
  #      context: ./KAFKA
  #      dockerfile: Dockerfile
  #  ports:
  #    - "9092:9092"
  #  links:
  #    - zookeeper:zk
  #  environment:
  #     KAFKA_ADVERTISED_PORT: 9092
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_ADVERTISED_HOST_NAME: 192.168.1.49
  #     KAFKA_CREATE_TOPICS: "passover-rooms-visitorcounts:1:1 passover-position-messages:1:1"
  #  volumes:
  #     - /Users/lucamarradi/Documents/DockerStaff/docker-compose-kafka-zookeeper/KAFKA/LOG-KAFKA:/tmp/kafka-logs
  #datamint:
  #   build: 
  #       context: ./DATAMINT
  #       dockerfile: Dockerfile
  #   container_name: datamint
  #   links:
  #    - kafka
  #   volumes:
  #     - /Users/lucamarradi/Documents/DockerStaff/docker-compose-kafka-zookeeper/DATAMINT/LOG-DATAMINT:/tmp/passover
       
